INSERT INTO public.state (id, initials, name) VALUES (12, 'AC', 'Acre');
INSERT INTO public.state (id, initials, name) VALUES (27, 'AL', 'Alagoas');
INSERT INTO public.state (id, initials, name) VALUES (16, 'AP', 'Amapá');
INSERT INTO public.state (id, initials, name) VALUES (13, 'AM', 'Amazonas');
INSERT INTO public.state (id, initials, name) VALUES (29, 'BA', 'Bahia');
INSERT INTO public.state (id, initials, name) VALUES (23, 'CE', 'Ceará');
INSERT INTO public.state (id, initials, name) VALUES (53, 'DF', 'Distrito Federal');
INSERT INTO public.state (id, initials, name) VALUES (32, 'ES', 'Espirito Santo');
INSERT INTO public.state (id, initials, name) VALUES (52, 'GO', 'Goiás');
INSERT INTO public.state (id, initials, name) VALUES (21, 'MA', 'Maranhão');
INSERT INTO public.state (id, initials, name) VALUES (51, 'MT', 'Mato Grosso');
INSERT INTO public.state (id, initials, name) VALUES (50, 'MS', 'Mato Grosso do Sul');
INSERT INTO public.state (id, initials, name) VALUES (31, 'MG', 'Minas Gerais');
INSERT INTO public.state (id, initials, name) VALUES (15, 'PA', 'Pará');
INSERT INTO public.state (id, initials, name) VALUES (25, 'PB', 'Paraíba');
INSERT INTO public.state (id, initials, name) VALUES (41, 'PR', 'Paraná');
INSERT INTO public.state (id, initials, name) VALUES (26, 'PE', 'Pernambuco');
INSERT INTO public.state (id, initials, name) VALUES (22, 'PI', 'Piauí');
INSERT INTO public.state (id, initials, name) VALUES (33, 'RJ', 'Rio de Janeiro');
INSERT INTO public.state (id, initials, name) VALUES (24, 'RN', 'Rio Grande do Norte');
INSERT INTO public.state (id, initials, name) VALUES (43, 'RS', 'Rio Grande do Sul');
INSERT INTO public.state (id, initials, name) VALUES (11, 'RO', 'Rondônia');
INSERT INTO public.state (id, initials, name) VALUES (14, 'RR', 'Roraima');
INSERT INTO public.state (id, initials, name) VALUES (42, 'SC', 'Santa Catarina');
INSERT INTO public.state (id, initials, name) VALUES (35, 'SP', 'São Paulo');
INSERT INTO public.state (id, initials, name) VALUES (28, 'SE', 'Sergipe');
INSERT INTO public.state (id, initials, name) VALUES (17, 'TO', 'Tocantins');